DROP VIEW IF EXISTS vw_movimentacoes_diarias;
DROP VIEW IF EXISTS vw_estoque_baixo;

DROP PROCEDURE IF EXISTS sp_dashboard_resumo;
DROP PROCEDURE IF EXISTS sp_dashboard_grafico_diario;
DROP PROCEDURE IF EXISTS sp_produtos_estoque_baixo;

ALTER TABLE usuarios DROP FOREIGN KEY fk_usuarios_empresa;
ALTER TABLE categorias DROP FOREIGN KEY fk_categorias_empresa;
ALTER TABLE fornecedores DROP FOREIGN KEY fk_fornecedores_empresa;
ALTER TABLE produtos DROP FOREIGN KEY fk_produtos_empresa;
ALTER TABLE produtos DROP FOREIGN KEY fk_produtos_categoria;
ALTER TABLE produtos DROP FOREIGN KEY fk_produtos_fornecedor;
ALTER TABLE movimentacoes_estoque DROP FOREIGN KEY fk_movimentacoes_empresa;
ALTER TABLE movimentacoes_estoque DROP FOREIGN KEY fk_movimentacoes_produto;
ALTER TABLE movimentacoes_estoque DROP FOREIGN KEY fk_movimentacoes_usuario;

RENAME TABLE
    empresas TO empresas_tmp,
    usuarios TO usuarios_tmp,
    categorias TO categorias_tmp,
    fornecedores TO fornecedores_tmp,
    produtos TO produtos_tmp,
    movimentacoes_estoque TO movimentacoes_estoque_tmp;

RENAME TABLE
    empresas_tmp TO EMPRESAS,
    usuarios_tmp TO USUARIOS,
    categorias_tmp TO CATEGORIAS,
    fornecedores_tmp TO FORNECEDORES,
    produtos_tmp TO PRODUTOS,
    movimentacoes_estoque_tmp TO MOVIMENTACOES_ESTOQUE;

ALTER TABLE EMPRESAS
    CHANGE COLUMN id ID BIGINT NOT NULL AUTO_INCREMENT,
    CHANGE COLUMN nome NOME VARCHAR(150) NOT NULL,
    CHANGE COLUMN cnpj CNPJ VARCHAR(18) NOT NULL,
    CHANGE COLUMN email EMAIL VARCHAR(150) NULL,
    CHANGE COLUMN telefone TELEFONE VARCHAR(20) NULL,
    CHANGE COLUMN ativo ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CHANGE COLUMN criado_em CRIADO_EM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE USUARIOS
    CHANGE COLUMN id ID BIGINT NOT NULL AUTO_INCREMENT,
    CHANGE COLUMN empresa_id EMPRESA_ID BIGINT NOT NULL,
    CHANGE COLUMN nome NOME VARCHAR(150) NOT NULL,
    CHANGE COLUMN email EMAIL VARCHAR(150) NOT NULL,
    CHANGE COLUMN senha SENHA VARCHAR(255) NOT NULL,
    CHANGE COLUMN perfil PERFIL ENUM('ADMIN', 'GERENTE', 'OPERADOR') NOT NULL DEFAULT 'OPERADOR',
    CHANGE COLUMN ativo ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CHANGE COLUMN token_recuperacao TOKEN_RECUPERACAO VARCHAR(255) NULL,
    CHANGE COLUMN token_recuperacao_expiracao TOKEN_RECUPERACAO_EXPIRACAO DATETIME NULL,
    CHANGE COLUMN criado_em CRIADO_EM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE CATEGORIAS
    CHANGE COLUMN id ID BIGINT NOT NULL AUTO_INCREMENT,
    CHANGE COLUMN empresa_id EMPRESA_ID BIGINT NOT NULL,
    CHANGE COLUMN nome NOME VARCHAR(100) NOT NULL,
    CHANGE COLUMN descricao DESCRICAO VARCHAR(255) NULL,
    CHANGE COLUMN ativo ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CHANGE COLUMN criado_em CRIADO_EM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE FORNECEDORES
    CHANGE COLUMN id ID BIGINT NOT NULL AUTO_INCREMENT,
    CHANGE COLUMN empresa_id EMPRESA_ID BIGINT NOT NULL,
    CHANGE COLUMN nome NOME VARCHAR(150) NOT NULL,
    CHANGE COLUMN cnpj CNPJ VARCHAR(18) NULL,
    CHANGE COLUMN email EMAIL VARCHAR(150) NULL,
    CHANGE COLUMN telefone TELEFONE VARCHAR(20) NULL,
    CHANGE COLUMN endereco ENDERECO VARCHAR(255) NULL,
    CHANGE COLUMN ativo ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CHANGE COLUMN criado_em CRIADO_EM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE PRODUTOS
    CHANGE COLUMN id ID BIGINT NOT NULL AUTO_INCREMENT,
    CHANGE COLUMN empresa_id EMPRESA_ID BIGINT NOT NULL,
    CHANGE COLUMN categoria_id CATEGORIA_ID BIGINT NULL,
    CHANGE COLUMN fornecedor_id FORNECEDOR_ID BIGINT NULL,
    CHANGE COLUMN nome NOME VARCHAR(150) NOT NULL,
    CHANGE COLUMN sku SKU VARCHAR(50) NOT NULL,
    CHANGE COLUMN descricao DESCRICAO TEXT NULL,
    CHANGE COLUMN preco PRECO DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    CHANGE COLUMN preco_custo PRECO_CUSTO DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    CHANGE COLUMN quantidade QUANTIDADE INT NOT NULL DEFAULT 0,
    CHANGE COLUMN quantidade_minima QUANTIDADE_MINIMA INT NOT NULL DEFAULT 0,
    CHANGE COLUMN url_imagem URL_IMAGEM VARCHAR(500) NULL,
    CHANGE COLUMN ativo ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    CHANGE COLUMN criado_em CRIADO_EM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHANGE COLUMN atualizado_em ATUALIZADO_EM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE MOVIMENTACOES_ESTOQUE
    CHANGE COLUMN id ID BIGINT NOT NULL AUTO_INCREMENT,
    CHANGE COLUMN empresa_id EMPRESA_ID BIGINT NOT NULL,
    CHANGE COLUMN produto_id PRODUTO_ID BIGINT NOT NULL,
    CHANGE COLUMN usuario_id USUARIO_ID BIGINT NOT NULL,
    CHANGE COLUMN tipo TIPO ENUM('ENTRADA', 'SAIDA', 'AJUSTE') NOT NULL,
    CHANGE COLUMN quantidade QUANTIDADE INT NOT NULL,
    CHANGE COLUMN motivo MOTIVO VARCHAR(255) NULL,
    CHANGE COLUMN criado_em CRIADO_EM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE USUARIOS
    ADD CONSTRAINT fk_usuarios_empresa FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS (ID);

ALTER TABLE CATEGORIAS
    ADD CONSTRAINT fk_categorias_empresa FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS (ID);

ALTER TABLE FORNECEDORES
    ADD CONSTRAINT fk_fornecedores_empresa FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS (ID);

ALTER TABLE PRODUTOS
    ADD CONSTRAINT fk_produtos_empresa FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS (ID),
    ADD CONSTRAINT fk_produtos_categoria FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIAS (ID) ON DELETE SET NULL,
    ADD CONSTRAINT fk_produtos_fornecedor FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDORES (ID) ON DELETE SET NULL;

ALTER TABLE MOVIMENTACOES_ESTOQUE
    ADD CONSTRAINT fk_movimentacoes_empresa FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS (ID),
    ADD CONSTRAINT fk_movimentacoes_produto FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTOS (ID),
    ADD CONSTRAINT fk_movimentacoes_usuario FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS (ID);

CREATE OR REPLACE VIEW vw_estoque_baixo AS
SELECT
    p.ID,
    p.NOME,
    p.SKU,
    p.QUANTIDADE,
    p.QUANTIDADE_MINIMA,
    (p.QUANTIDADE_MINIMA - p.QUANTIDADE) AS deficit,
    p.EMPRESA_ID
FROM PRODUTOS p
WHERE p.QUANTIDADE < p.QUANTIDADE_MINIMA
  AND p.ATIVO = TRUE
ORDER BY deficit DESC;

CREATE OR REPLACE VIEW vw_movimentacoes_diarias AS
SELECT
    DATE(me.CRIADO_EM)                                                      AS data,
    p.EMPRESA_ID,
    SUM(CASE WHEN me.TIPO = 'ENTRADA' THEN me.QUANTIDADE ELSE 0 END)        AS entradas,
    SUM(CASE WHEN me.TIPO = 'SAIDA'   THEN me.QUANTIDADE ELSE 0 END)        AS saidas,
    SUM(CASE WHEN me.TIPO = 'AJUSTE'  THEN me.QUANTIDADE ELSE 0 END)        AS ajustes
FROM MOVIMENTACOES_ESTOQUE me
         JOIN PRODUTOS p ON me.PRODUTO_ID = p.ID
WHERE me.CRIADO_EM >= DATE_SUB(NOW(), INTERVAL 7 DAY)
GROUP BY DATE(me.CRIADO_EM), p.EMPRESA_ID
ORDER BY data ASC;

CREATE PROCEDURE sp_dashboard_resumo(IN p_empresa_id BIGINT)
SELECT
    (SELECT COUNT(*)
     FROM PRODUTOS p
     WHERE p.EMPRESA_ID = p_empresa_id
       AND p.ATIVO = TRUE)                                                   AS total_produtos,
    (SELECT COUNT(*)
     FROM CATEGORIAS c
     WHERE c.EMPRESA_ID = p_empresa_id
       AND c.ATIVO = TRUE)                                                   AS total_categorias,
    (SELECT COUNT(*)
     FROM FORNECEDORES f
     WHERE f.EMPRESA_ID = p_empresa_id
       AND f.ATIVO = TRUE)                                                   AS total_fornecedores,
    COALESCE((
        SELECT SUM(p.PRECO * p.QUANTIDADE)
        FROM PRODUTOS p
        WHERE p.EMPRESA_ID = p_empresa_id
          AND p.ATIVO = TRUE
    ), 0)                                                                    AS valor_total_estoque,
    (SELECT COUNT(*)
     FROM PRODUTOS p
     WHERE p.EMPRESA_ID = p_empresa_id
       AND p.ATIVO = TRUE
       AND p.QUANTIDADE <= p.QUANTIDADE_MINIMA)                              AS produtos_abaixo_minimo,
    (SELECT COUNT(*)
     FROM MOVIMENTACOES_ESTOQUE me
     WHERE me.EMPRESA_ID = p_empresa_id
       AND MONTH(me.CRIADO_EM) = MONTH(CURRENT_DATE())
       AND YEAR(me.CRIADO_EM) = YEAR(CURRENT_DATE()))                        AS movimentacoes_mes;

CREATE PROCEDURE sp_dashboard_grafico_diario(IN p_empresa_id BIGINT, IN p_dias INT)
SELECT
    DATE_FORMAT(me.CRIADO_EM, '%d/%m')                                       AS data,
    SUM(CASE WHEN me.TIPO = 'ENTRADA' THEN 1 ELSE 0 END)                     AS entradas,
    SUM(CASE WHEN me.TIPO = 'SAIDA' THEN 1 ELSE 0 END)                       AS saidas,
    SUM(CASE WHEN me.TIPO = 'AJUSTE' THEN 1 ELSE 0 END)                      AS ajustes
FROM MOVIMENTACOES_ESTOQUE me
WHERE me.EMPRESA_ID = p_empresa_id
  AND me.CRIADO_EM >= DATE_SUB(CURDATE(), INTERVAL (p_dias - 1) DAY)
GROUP BY DATE(me.CRIADO_EM), DATE_FORMAT(me.CRIADO_EM, '%d/%m')
ORDER BY DATE(me.CRIADO_EM);

CREATE PROCEDURE sp_produtos_estoque_baixo(IN p_empresa_id BIGINT)
SELECT
    p.ID,
    p.NOME,
    p.SKU,
    p.QUANTIDADE,
    p.QUANTIDADE_MINIMA,
    (p.QUANTIDADE_MINIMA - p.QUANTIDADE) AS deficit
FROM PRODUTOS p
WHERE p.EMPRESA_ID = p_empresa_id
  AND p.ATIVO = TRUE
  AND p.QUANTIDADE < p.QUANTIDADE_MINIMA
ORDER BY deficit DESC, p.NOME;
